version: "3.8"
services:
#  sonarqube:
#    image: sonarqube:9.3.0-community
#    container_name: online-banking-backend-sonarqube
#    command: "-Dsonar.search.javaAdditionalOpts=-Dnode.store.allow_mmap=false"
#    depends_on:
#      - postgres
#    environment:
#      SONAR_JDBC_URL: jdbc:postgresql://postgres:5432/sonar
#      SONAR_JDBC_USERNAME: sonar
#      SONAR_JDBC_PASSWORD: sonar
#    volumes:
#      - ./docker-volumes/sonarqube/sonarqube_conf:/opt/sonarqube/conf
#      - ./docker-volumes/sonarqube/sonarqube_data:/opt/sonarqube/data
#      - ./docker-volumes/sonarqube/sonarqube_extensions:/opt/sonarqube/extensions
#      - ./docker-volumes/sonarqube/sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
#    ports:
#      - "9000:9000"
#    networks:
#      - online-banking-backend
#      
#  postgres:
#    image: postgres:14-alpine3.15
#    container_name: online-banking-backend-postgres
#    environment:
#      POSTGRES_USER: sonar
#      POSTGRES_PASSWORD: sonar
#    volumes:
#      - ./docker-volumes/postgres/postgresql:/var/lib/postgresql
#      - ./docker-volumes/postgres/postgresql_data:/var/lib/postgresql/data
#    networks:
#      - online-banking-backend
      
  db:
    image: mysql:8.0.28
    container_name: online-banking-backend-mysql
    environment:
      MYSQL_DATABASE: bitbank
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_USER: user
    ports:
      - "3306:3306"
    volumes:
      - ./dockerfiles/mysql:/docker-entrypoint-initdb.d
    networks:
      - online-banking-backend
      
  adminer:
    image: adminer:4.8.1-standalone
    container_name: online-banking-backend-adminer
    ports:
      - "7000:8080"
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - online-banking-backend

  
networks:
  online-banking-backend:
    name: online-banking-backend
    driver: bridge