version: "3.8"
services:
  db:
    image: mysql:8.0.31
    container_name: online-banking-backend-mysql
    environment:
      MYSQL_DATABASE: bitbank
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_USER: user
    ports:
      - "3306:3306"
    volumes:
      - ./dockerfiles/development/mysql:/docker-entrypoint-initdb.d
    networks:
      - online-banking-backend
      
  adminer:
    image: adminer:4.8.1-standalone
    container_name: online-banking-backend-adminer
    ports:
      - "7000:8080"
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - online-banking-backend

  
networks:
  online-banking-backend:
    name: online-banking-backend
    driver: bridge
