version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.5
    steps:
      - checkout
      - run: ./mvnw -Dmaven.test.skip=true package
      - persist_to_workspace:
         root: ./
         paths:
           - target/

  test:
    docker:
      - image: cimg/openjdk:17.0.5
    steps:
      - checkout
      - attach_workspace:
          at: ./target
      - run: ./mvnw test jacoco:report

workflows:
  version: 2

  ci-cd-pipeline:
    jobs:
      - build
      - test:
          requires:
            - build